[package]
name = "serror"
description = "serialize anyhow errors into json format"
version = "0.3.0"
edition = "2021"
authors = ["MoghTech"]
repository = "https://github.com/mbecker20/serror"
license = "MIT"

[features]
default = ["axum"]
axum = ["dep:axum", "dep:axum-extra"]

[dependencies]
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
anyhow = "1.0.82"
# axum feature
axum = { version = "0.7.5", optional = true }
axum-extra = { version = "0.9.3", features = ["typed-header"], optional = true }
